### ISSUE TITLE
You incorrectly copied the CMakeLists.txt -- missed FOREACH(var ${EXECUTABLES})

### ISSUE THREAD

**Issue by or-else** [alyssaq/stasm_build#1]
Did you actually test your scripts?

root@21733c94ddf4:/source/stasm/build# cmake ../
CMake Error at CMakeLists.txt:129 (add_executable):
  add_executable called with incorrect number of arguments

CMake Error at CMakeLists.txt:131 (ENDFOREACH):
  endforeach An ENDFOREACH command was found outside of a proper FOREACH
  ENDFOREACH structure.  Or its arguments did not match the opening FOREACH
  command.

-- Configuring incomplete, errors occurred!

**Comment by alyssaq** [comment]
Finally took the time to fix this script. Should work now :)
