### ISSUE TITLE
make: *** No targets specified and no makefile found.

### ISSUE THREAD

**Issue by SunsetWan** [alyssaq/stasm_build#3]
Hello, @alyssaq 
![screen shot 2018-04-01 at 8 05 26 pm](https://user-images.githubusercontent.com/16316111/38172952-2cf12974-35e8-11e8-8313-d132f8f62947.png)
Here is my problem. Actually, I can't find facedet.cpp file located at "/Users/sunsetwan/Downloads/stasm4.1.0/stasm_build/stasm/MOD_1/facedet.cpp".
Can you give me suggestions about the solution to this weird problem?

**Comment by alyssaq** [comment]
the `stasm_build` should be cloned in the `stasm4.1.0` folder.
Run build.sh in the `stasm4.1.0` folder:
```
$ ./stasm_build/build.sh
```

**Comment by SunsetWan** [comment]
Hello, alyssaq
![screen shot 2018-04-01 at 8 56 39 pm](https://user-images.githubusercontent.com/16316111/38173333-443e93e4-35ef-11e8-8a0d-5ee5349d8c72.png)
It seems that I still met the same problem 

> "make: *** No targets specified and no makefile found.  Stop."

> "CMake Error: The source directory "/Users/sunsetwan/Downloads" does not appear to contain CMakeLists.txt."

 I noticed it, but my actual working path is /Users/sunsetwan/Downloads/stasm4.1.0. Why is the path which the prompt warned me "/Users/sunsetwan/Downloads" ?

Thanks for your reply.

**Comment by alyssaq** [comment]
Ah, its because the `build` folder already exists. Ive updated the script to check for the folder.

Could you please untar stasm4.1.0.tar.gz and run the steps again:
```
$ cd stasm4.1.0
$ git clone https://github.com/alyssaq/stasm_build.git
$ ./stasm_build/build.sh
```

**Comment by SunsetWan** [comment]
WOW! I made it! Thank you so much!

**Comment by alyssaq** [comment]
Fantastic! 🎉
